// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package imsdb

import (
	"context"
)

type Querier interface {
	ActionLogs(ctx context.Context, db DBTX, arg ActionLogsParams) ([]ActionLogsRow, error)
	AddActionLog(ctx context.Context, db DBTX, arg AddActionLogParams) (int64, error)
	AddEventAccess(ctx context.Context, db DBTX, arg AddEventAccessParams) (int64, error)
	AttachFieldReportToIncident(ctx context.Context, db DBTX, arg AttachFieldReportToIncidentParams) error
	AttachIncidentTypeToIncident(ctx context.Context, db DBTX, arg AttachIncidentTypeToIncidentParams) error
	AttachRangerHandleToIncident(ctx context.Context, db DBTX, arg AttachRangerHandleToIncidentParams) error
	AttachRangerToStay(ctx context.Context, db DBTX, arg AttachRangerToStayParams) error
	AttachReportEntryToFieldReport(ctx context.Context, db DBTX, arg AttachReportEntryToFieldReportParams) error
	AttachReportEntryToIncident(ctx context.Context, db DBTX, arg AttachReportEntryToIncidentParams) error
	AttachReportEntryToStay(ctx context.Context, db DBTX, arg AttachReportEntryToStayParams) error
	AttachStayToIncident(ctx context.Context, db DBTX, arg AttachStayToIncidentParams) error
	ClearEventAccessForExpression(ctx context.Context, db DBTX, arg ClearEventAccessForExpressionParams) error
	ClearEventAccessForMode(ctx context.Context, db DBTX, arg ClearEventAccessForModeParams) error
	ConcentricStreets(ctx context.Context, db DBTX, event int32) ([]ConcentricStreetsRow, error)
	CreateConcentricStreet(ctx context.Context, db DBTX, arg CreateConcentricStreetParams) error
	CreateDestination(ctx context.Context, db DBTX, arg CreateDestinationParams) error
	CreateEvent(ctx context.Context, db DBTX, arg CreateEventParams) (int64, error)
	CreateFieldReport(ctx context.Context, db DBTX, arg CreateFieldReportParams) error
	CreateIncident(ctx context.Context, db DBTX, arg CreateIncidentParams) (int64, error)
	CreateIncidentType(ctx context.Context, db DBTX, arg CreateIncidentTypeParams) (int64, error)
	CreateReportEntry(ctx context.Context, db DBTX, arg CreateReportEntryParams) (int64, error)
	CreateStay(ctx context.Context, db DBTX, arg CreateStayParams) (int64, error)
	Destinations(ctx context.Context, db DBTX, arg DestinationsParams) ([]DestinationsRow, error)
	DetachIncidentTypeFromIncident(ctx context.Context, db DBTX, arg DetachIncidentTypeFromIncidentParams) error
	DetachRangerFromStay(ctx context.Context, db DBTX, arg DetachRangerFromStayParams) error
	DetachRangerHandleFromIncident(ctx context.Context, db DBTX, arg DetachRangerHandleFromIncidentParams) error
	Event(ctx context.Context, db DBTX, id int32) (EventRow, error)
	EventAccessAll(ctx context.Context, db DBTX) ([]EventAccessAllRow, error)
	// This returns access for a target event, as well as for that event's
	// parent group, if any. If the target event *is* a group, this query
	// will return nothing. That's intentional, and it helps prevent people
	// from adding incidents or FRs to event groups as though those were events.
	EventAndParentAccess(ctx context.Context, db DBTX, arg EventAndParentAccessParams) ([]EventAndParentAccessRow, error)
	Events(ctx context.Context, db DBTX) ([]EventsRow, error)
	FieldReport(ctx context.Context, db DBTX, arg FieldReportParams) (FieldReportRow, error)
	FieldReport_ReportEntries(ctx context.Context, db DBTX, arg FieldReport_ReportEntriesParams) ([]FieldReport_ReportEntriesRow, error)
	FieldReports(ctx context.Context, db DBTX, event int32) ([]FieldReportsRow, error)
	FieldReports_ReportEntries(ctx context.Context, db DBTX, arg FieldReports_ReportEntriesParams) ([]FieldReports_ReportEntriesRow, error)
	Incident(ctx context.Context, db DBTX, arg IncidentParams) (IncidentRow, error)
	IncidentType(ctx context.Context, db DBTX, id int32) (IncidentTypeRow, error)
	IncidentTypes(ctx context.Context, db DBTX) ([]IncidentTypesRow, error)
	Incident_LinkedIncidents(ctx context.Context, db DBTX, arg Incident_LinkedIncidentsParams) ([]Incident_LinkedIncidentsRow, error)
	Incident_Rangers(ctx context.Context, db DBTX, arg Incident_RangersParams) ([]Incident_RangersRow, error)
	Incident_ReportEntries(ctx context.Context, db DBTX, arg Incident_ReportEntriesParams) ([]Incident_ReportEntriesRow, error)
	Incidents(ctx context.Context, db DBTX, event int32) ([]IncidentsRow, error)
	Incidents_Rangers(ctx context.Context, db DBTX, event int32) ([]Incidents_RangersRow, error)
	Incidents_ReportEntries(ctx context.Context, db DBTX, arg Incidents_ReportEntriesParams) ([]Incidents_ReportEntriesRow, error)
	LinkIncidents(ctx context.Context, db DBTX, arg LinkIncidentsParams) error
	// This doesn't use "MAX" because sqlc can't figure out the type for aggregations :(.
	NextFieldReportNumber(ctx context.Context, db DBTX, event int32) (int32, error)
	// This doesn't use "MAX" because sqlc can't figure out the type for aggregations :(.
	NextIncidentNumber(ctx context.Context, db DBTX, event int32) (int32, error)
	// This doesn't use "MAX" because sqlc can't figure out the type for aggregations :(.
	NextStayNumber(ctx context.Context, db DBTX, event int32) (int32, error)
	QueryEventID(ctx context.Context, db DBTX, name string) (QueryEventIDRow, error)
	RemoveDestinations(ctx context.Context, db DBTX, arg RemoveDestinationsParams) error
	SchemaVersion(ctx context.Context, db DBTX) (int16, error)
	SetFieldReportReportEntryStricken(ctx context.Context, db DBTX, arg SetFieldReportReportEntryStrickenParams) error
	//
	// The "stricken" queries seem bloated at first blush, because the whole
	// "where ID in (..." could just be "where ID =". What it's doing though is
	// ensuring that the provided eventID and incidentNumber actually align with
	// the reportEntryID in question, and that's important for authorization purposes.
	//
	SetIncidentReportEntryStricken(ctx context.Context, db DBTX, arg SetIncidentReportEntryStrickenParams) error
	SetStayReportEntryStricken(ctx context.Context, db DBTX, arg SetStayReportEntryStrickenParams) error
	Stay(ctx context.Context, db DBTX, arg StayParams) (StayRow, error)
	Stay_Rangers(ctx context.Context, db DBTX, arg Stay_RangersParams) ([]Stay_RangersRow, error)
	Stay_ReportEntries(ctx context.Context, db DBTX, arg Stay_ReportEntriesParams) ([]Stay_ReportEntriesRow, error)
	Stays(ctx context.Context, db DBTX, event int32) ([]StaysRow, error)
	Stays_Rangers(ctx context.Context, db DBTX, event int32) ([]Stays_RangersRow, error)
	Stays_ReportEntries(ctx context.Context, db DBTX, arg Stays_ReportEntriesParams) ([]Stays_ReportEntriesRow, error)
	UnlinkIncidents(ctx context.Context, db DBTX, arg UnlinkIncidentsParams) error
	UpdateEvent(ctx context.Context, db DBTX, arg UpdateEventParams) error
	UpdateFieldReport(ctx context.Context, db DBTX, arg UpdateFieldReportParams) error
	UpdateIncident(ctx context.Context, db DBTX, arg UpdateIncidentParams) error
	UpdateIncidentType(ctx context.Context, db DBTX, arg UpdateIncidentTypeParams) error
	UpdateStay(ctx context.Context, db DBTX, arg UpdateStayParams) error
}

var _ Querier = (*Queries)(nil)
