# Don't add a comment to GitHub conversation if there is no coverage change.
comment:
  require_changes: true

# Require 100% diff coverage, only complain about project coverage.
coverage:
  status:
    project:
      default:
        informational: true
        target: 100%
    patch:
      default:
        informational: false
        target: 100%

ignore:
  # These are glorified shell scripts in the form of Go programs (for cross-platform use),
  # and they are separate from the server program.
  - "bin/build"
  # This is generated code from templ.
  - "web/template/*.go"
  # These are generated code from sqlc.
  - "store/imsdb/*.go"
  - "directory/clubhousedb/*.go"
