services:

  app:
    build: .
    image: "ranger-ims-go:${IMAGE_TAG:-latest}"
    container_name: "ranger-ims-go"
    environment:
      # This is a totally empty user directory, so no one will be able to log in.
      # We can't use a ClubhouseDB directory here because CI doesn't have one to
      # access, and we can't use a Fake directory, because CI builds of IMS don't
      # compile the fake MySQL server into the program. If people want to use
      # docker compose for local dev, we should make a separate Dockerfile and
      # docker-compose.yml for that.
      IMS_DIRECTORY: "NoOp"
      IMS_DB_HOST_NAME: "ranger-ims-database"
      IMS_DB_PORT: "${IMS_DB_PORT:-3306}"
      IMS_DB_USER_NAME: "${IMS_DB_USER_NAME:-ims}"
      IMS_DB_PASSWORD: "${IMS_DB_PASSWORD:-ims}"
    ports:
      - "${IMS_PORT:-8080}:80"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "/opt/ims/bin/ims", "healthcheck", "--server_url", "http://app:80" ]
      interval: 1s
      timeout: 3s
      retries: 30

  database:
    image: "mariadb:10.5.27"
    container_name: "ranger-ims-database"
    environment:
      MARIADB_DATABASE: "${IMS_DB_DATABASE:-ims}"
      MARIADB_USER: "${IMS_DB_USER_NAME:-ims}"
      MARIADB_PASSWORD: "${IMS_DB_PASSWORD:-ims}"
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "${IMS_DB_PORT:-3306}"
    volumes:
      - ./.docker/mysql/data/:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 1s
      timeout: 5s
      retries: 10
