services:

  app:
    image: "ranger-ims-go:${TAG}"
    container_name: "ranger-ims-go"
    environment:
      IMS_DIRECTORY: "TestUsers"
      IMS_DB_HOST_NAME: "ranger-ims-database"
      IMS_DB_PORT: "${IMS_DB_PORT:-3306}"
      IMS_DB_USER_NAME: "${IMS_DB_USER_NAME:-ims}"
      IMS_DB_PASSWORD: "${IMS_DB_PASSWORD:-ims}"
    ports:
      - "${IMS_PORT:-8080}:80"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "/ranger-ims-go", "healthcheck", "--server_url", "http://app:80" ]
      interval: 1s
      timeout: 3s
      retries: 30

  database:
    image: "mariadb:10.5.27"
    container_name: "ranger-ims-database"
    environment:
      MARIADB_DATABASE: "${IMS_DB_DATABASE:-ims}"
      MARIADB_USER: "${IMS_DB_USER_NAME:-ims}"
      MARIADB_PASSWORD: "${IMS_DB_PASSWORD:-ims}"
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "${IMS_DB_PORT:-3306}"
    volumes:
      - ./.docker/mysql/data/:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 1s
      timeout: 5s
      retries: 10
