// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
//

// See the file COPYRIGHT for copyright information.

//

// Licensed under the Apache License, Version 2.0 (the "License");

// you may not use this file except in compliance with the License.

// You may obtain a copy of the License at

//

//     http://www.apache.org/licenses/LICENSE-2.0

//

// Unless required by applicable law or agreed to in writing, software

// distributed under the License is distributed on an "AS IS" BASIS,

// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

// See the License for the specific language governing permissions and

// limitations under the License.

//

package template

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Destinations(deployment, versionName, versionRef, eventName string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Head("Destinations | "+eventName, "destinations.js", true).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<body><div class=\"container-fluid\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Header(deployment).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Nav(eventName).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<h1 id=\"doc-title\">Destinations</h1><div id=\"error_info\" class=\"hidden text-danger\"><p id=\"error_text\"></p></div><div class=\"row\"><div id=\"button_container\" class=\"col-sm-7\"><button id=\"show_rows\" type=\"button\" class=\"btn btn-light btn-sm dropdown-toggle\" data-bs-toggle=\"dropdown\"><span class=\"selection\">All Rows</span></button><ul class=\"dropdown-menu\"><li id=\"show_rows_all\"><a href=\"#\" class=\"name dropdown-item\" onclick=\"destShowRows('all', true); return false;\">All Rows</a></li><li id=\"show_rows_25\"><a href=\"#\" class=\"name dropdown-item\" onclick=\"destShowRows('25', true); return false;\">25 Rows</a></li><li id=\"show_rows_50\"><a href=\"#\" class=\"name dropdown-item\" onclick=\"destShowRows('50', true); return false;\">50 Rows</a></li><li id=\"show_rows_100\"><a href=\"#\" class=\"name dropdown-item\" onclick=\"destShowRows('100', true); return false;\">100 Rows</a></li><li class=\"border-top\"><a href=\"/ims/app/settings\" class=\"name dropdown-item\">Change default</a></li></ul></div><div id=\"search_container\" class=\"form-group form-group-sm col-sm-5\"><div class=\"flex-input-container no-print\"><label for=\"search_input\" class=\"control-label hidden\" aria-label=\"Search\">Search</label> <input id=\"search_input\" type=\"search\" class=\"form-control search-box\" placeholder=\"Press &quot; ⁄ &quot; to search\" inputmode=\"latin\" autocomplete=\"off\" aria-controls=\"destinations_table\"></div></div></div><table id=\"destinations_table\" class=\"table table-striped table-hover\"><thead><tr><th>Name</th><th>Address</th><th>Type</th><th>Description</th></tr></thead> <tbody></tbody><tfoot><tr><th>Name</th><th>Address</th><th>Type</th><th>Description</th></tr></tfoot></table>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Footer(versionName, versionRef).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
