// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
//

// See the file COPYRIGHT for copyright information.

//

// Licensed under the Apache License, Version 2.0 (the "License");

// you may not use this file except in compliance with the License.

// You may obtain a copy of the License at

//

//     http://www.apache.org/licenses/LICENSE-2.0

//

// Unless required by applicable law or agreed to in writing, software

// distributed under the License is distributed on an "AS IS" BASIS,

// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

// See the License for the specific language governing permissions and

// limitations under the License.

//

package template

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Search(deployment, versionName, versionRef string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Head("Search", "search.js", false, versionRef).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<body><div class=\"container-fluid\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Header(deployment).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Nav("").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<h1 id=\"doc-title\">Search</h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ErrorInfo().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<p class=\"no-print\">Search Incidents, Field Reports, and Visits across every Event you have access to.</p><div class=\"row\"><div id=\"search_container\" class=\"form-group form-group-sm col-sm-6\"><div class=\"flex-input-container no-print\"><label for=\"search_input\" class=\"control-label hidden\" aria-label=\"Search\">Search</label> <input id=\"search_input\" type=\"search\" class=\"form-control search-box\" placeholder=\"Press &quot; ⁄ &quot; to search\" inputmode=\"latin\" autocomplete=\"off\" aria-controls=\"search_results_table\"></div></div><div class=\"col-sm-6 no-print\"><div class=\"form-check form-check-inline\"><input class=\"form-check-input\" type=\"checkbox\" id=\"kind_incident\" checked> <label class=\"form-check-label\" for=\"kind_incident\">Incidents</label></div><div class=\"form-check form-check-inline\"><input class=\"form-check-input\" type=\"checkbox\" id=\"kind_field_report\" checked> <label class=\"form-check-label\" for=\"kind_field_report\">Field Reports</label></div><div class=\"form-check form-check-inline\"><input class=\"form-check-input\" type=\"checkbox\" id=\"kind_visit\" checked> <label class=\"form-check-label\" for=\"kind_visit\">Visits</label></div></div></div><p id=\"search_results_info\" class=\"text-body-secondary\"></p><table id=\"search_results_table\" class=\"table table-striped table-hover\"><thead><tr><th>Event</th><th>Type</th><th>#</th><th>Created</th><th>Summary</th><th>Excerpt</th></tr></thead> <tbody></tbody></table><template id=\"search_result_row_template\"><tr><td class=\"result-event\"></td><td class=\"result-kind\"></td><td class=\"result-number\"><a></a></td><td class=\"result-created\"></td><td class=\"result-summary\"></td><td class=\"result-snippet text-body-secondary\"></td></tr></template>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Footer(versionName, versionRef).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
