//
// See the file COPYRIGHT for copyright information.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Shared helpers for the Vitest tests in this directory.

import { readFileSync } from "node:fs";
import { join } from "node:path";
import process from "node:process";
import { vi } from "vitest";

// Replace the current document with a templ-rendered HTML fixture from the
// fixtures directory (generated by bin/rendertestfixtures, via `npm test`).
//
// Page modules look up their elements and run their init function at module
// import time, so tests must call this BEFORE dynamically importing the page
// module under test.
export function loadFixture(name: string): void {
    const html = readFileSync(join(process.cwd(), "web", "typescripttest", "fixtures", name), "utf8");
    document.open();
    document.write(html);
    document.close();
    // happy-dom's page parser drops table elements (like <tr>) that sit inside
    // a <template> without a surrounding <table>, even though the HTML spec
    // allows them there. Re-parse each template's content from the raw fixture
    // HTML, which takes the innerHTML path that happy-dom handles correctly.
    for (const match of html.matchAll(/<template id="([^"]+)">([\s\S]*?)<\/template>/g)) {
        const template = document.getElementById(match[1]!) as HTMLTemplateElement | null;
        if (template != null) {
            template.innerHTML = match[2]!;
        }
    }
}

// Make a JSON Response like the IMS API would return. fetchNoThrow only
// parses the body when the content-type is exactly "application/json".
export function jsonResponse(body: unknown, status: number = 200): Response {
    return new Response(JSON.stringify(body), {
        status: status,
        headers: { "content-type": "application/json" },
    });
}

// Make an "application/problem+json" error Response, as returned by the
// server's herr package.
export function problemResponse(detail: string, status: number): Response {
    return new Response(JSON.stringify({ detail: detail, status: status }), {
        status: status,
        headers: { "content-type": "application/problem+json" },
    });
}

export type FetchHandler = (url: string, init?: RequestInit) => Response | undefined;

// Replace global fetch with a route handler, returning the mock function so
// that tests can inspect calls. Returning undefined from the handler rejects
// the fetch, which surfaces in fetchNoThrow's err result.
export function mockFetch(handler: FetchHandler) {
    const mock = vi.fn(async (url: string, init?: RequestInit): Promise<Response> => {
        const response = handler(url, init);
        if (response == null) {
            throw new Error(`no mocked fetch route for ${url}`);
        }
        return response;
    });
    vi.stubGlobal("fetch", mock);
    return mock;
}

type FlatpickrHook = (selectedDates: Date[], dateStr: string, instance: MockFlatpickr) => void;

interface FlatpickrOptionsLike {
    altFormat?: string;
    onReady?: FlatpickrHook;
    onChange?: FlatpickrHook;
    onClose?: FlatpickrHook;
}

// A minimal stand-in for the flatpickr date picker, which production pages
// load as a classic script. It mirrors the parts of the Flatpickr interface
// that ims.ts uses: altInput creation, _flatpickr on the input element,
// setDate, and the onReady/onChange hooks. setup.ts installs the factory as
// the flatpickr global; tests can inspect MockFlatpickr.instances and call
// setDate(date, true) to simulate the user picking a date.
export class MockFlatpickr {
    static instances: MockFlatpickr[] = [];

    config: FlatpickrOptionsLike;
    selectedDates: Date[] = [];
    input: HTMLInputElement;
    altInput: HTMLInputElement;

    constructor(selector: string | Node, opts: FlatpickrOptionsLike) {
        this.config = opts;
        const input = typeof selector === "string" ? document.querySelector(selector) : selector;
        if (!(input instanceof HTMLInputElement)) {
            throw new Error(`no input element for flatpickr selector ${selector}`);
        }
        this.input = input;
        this.altInput = document.createElement("input");
        this.input.insertAdjacentElement("afterend", this.altInput);
        (this.input as HTMLInputElement & { _flatpickr: MockFlatpickr })._flatpickr = this;
        opts.onReady?.([], "", this);
        MockFlatpickr.instances.push(this);
    }

    setDate(date: Date | string | Date[], triggerChange: boolean, _format?: string): void {
        const first = Array.isArray(date) ? date[0]! : date;
        const parsed = first instanceof Date ? first : new Date(first);
        this.selectedDates = [parsed];
        this.altInput.value = parsed.toISOString();
        if (triggerChange) {
            this.config.onChange?.(this.selectedDates, this.altInput.value, this);
        }
    }

    parseDate(date: string | number, _format: string): Date {
        return new Date(date);
    }
}

// A minimal stand-in for EventSource, which happy-dom doesn't implement.
// setup.ts installs this as the EventSource global; tests can inspect
// MockEventSource.instances and dispatch MessageEvents at them.
export class MockEventSource extends EventTarget {
    static instances: MockEventSource[] = [];

    static readonly CONNECTING = 0;
    static readonly OPEN = 1;
    static readonly CLOSED = 2;

    url: string;
    withCredentials: boolean;
    readyState: number = MockEventSource.CONNECTING;

    constructor(url: string, init?: { withCredentials?: boolean }) {
        super();
        this.url = url;
        this.withCredentials = init?.withCredentials ?? false;
        MockEventSource.instances.push(this);
    }

    close(): void {
        this.readyState = MockEventSource.CLOSED;
    }
}

interface DataTableColumn {
    name?: string;
    data?: string;
    render?: (value: any, type: string, row: any) => unknown;
}
interface DataTableOptions {
    ajax: (data: unknown, callback: (resp: { data: any[] }) => void, settings: unknown) => void;
    columns: DataTableColumn[];
    createdRow?: (row: HTMLElement, data: any, index: number) => void;
}

// A minimal stand-in for the DataTables grid that the list pages (incidents,
// field_reports, sanctuary_visits, places) construct as a classic-script
// dependency. It captures the options the page passes, runs the ajax data
// source (so the page's row transforms and fetches are exercised), and fires
// the "init" listeners once the first load completes. The methods the pages
// call for filtering/paging are present as no-ops that record nothing, since
// those drive the real DataTables rendering that isn't under test here.
//
// Install it per-test with vi.stubGlobal("DataTable", MockDataTable), then read
// MockDataTable.lastInstance.data() to see the rows the page handed the table.
export class MockDataTable {
    static lastInstance: MockDataTable | null = null;
    static ext = { errMode: "" };
    static render = {
        text: () => ({ display: (s: unknown): unknown => s }),
        number: () => ({ display: (s: unknown): unknown => s }),
    };

    options: DataTableOptions;
    private rowData: any[] = [];
    private initHandlers: (() => void)[] = [];

    page = { len: (_n: number | null): void => {} };
    ajax = { reload: (_data?: unknown, _draw?: boolean): void => void this.runAjax(false) };
    row = { add: (json: any): MockDataTable => { this.rowData.push(json); return this; } };
    // search(q, isRegex, smart) with a .fixed(name, fn) sub-method.
    search = Object.assign((..._args: unknown[]): void => {}, {
        fixed: (..._args: unknown[]): void => {},
    });

    constructor(_selector: string, options: DataTableOptions) {
        this.options = options;
        MockDataTable.lastInstance = this;
        void this.runAjax(true);
    }

    on(event: string, cb: () => void): MockDataTable {
        if (event === "init") {
            this.initHandlers.push(cb);
        }
        return this;
    }

    data(): any[] {
        return this.rowData;
    }

    draw(_paging?: unknown): MockDataTable {
        return this;
    }

    processing(_show: boolean): MockDataTable {
        return this;
    }

    rows() {
        const rowData = this.rowData;
        return {
            every(this: void, cb: (this: { data: () => any }) => void): void {
                for (const datum of rowData) {
                    cb.call({ data: (): any => datum });
                }
            },
        };
    }

    column(name: string): DataTableColumn | undefined {
        return this.options.columns.find(c => c.name === name);
    }

    private async runAjax(fireInit: boolean): Promise<void> {
        await new Promise<void>((resolve): void => {
            this.options.ajax(null, (resp): void => {
                this.rowData = resp.data;
                resolve();
            }, null);
        });
        if (fireInit) {
            // The page registers its "init" handler synchronously right after
            // constructing the table, so it's in place by the time the first
            // (awaited) load resolves here.
            for (const cb of this.initHandlers) {
                cb();
            }
        }
    }
}
