// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package clubhousedb

import (
	"context"
)

type Querier interface {
	PersonPositions(ctx context.Context, db DBTX) ([]PersonPosition, error)
	PersonTeams(ctx context.Context, db DBTX) ([]PersonTeamsRow, error)
	// Filter persons to those with statuses that may be of interest to IMS.
	// These Persons results are used to determine who may log into IMS, and also
	// to determine who shows up in the Incident page's "Add Ranger" section.
	//
	// This intentionally excludes statuses like bonked, echelon, deceased, resigned, and retired,
	// as those persons should not be able to log into IMS nor be granted any permissions in IMS.
	Persons(ctx context.Context, db DBTX) ([]PersonsRow, error)
	PersonsOnDuty(ctx context.Context, db DBTX) ([]PersonsOnDutyRow, error)
	Positions(ctx context.Context, db DBTX) ([]PositionsRow, error)
	Teams(ctx context.Context, db DBTX) ([]TeamsRow, error)
}

var _ Querier = (*Queries)(nil)
