// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package clubhousedb

import (
	"context"
)

type Querier interface {
	PersonPositions(ctx context.Context, db DBTX) ([]PersonPosition, error)
	PersonTeams(ctx context.Context, db DBTX) ([]PersonTeamsRow, error)
	Positions(ctx context.Context, db DBTX) ([]PositionsRow, error)
	RangersById(ctx context.Context, db DBTX) ([]RangersByIdRow, error)
	Teams(ctx context.Context, db DBTX) ([]TeamsRow, error)
}

var _ Querier = (*Queries)(nil)
