# Docs: https://docs.github.com/en/actions

name: CI/CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden CI
      uses: step-security/harden-runner@v2.12.0
      with:
        egress-policy: block
        allowed-endpoints: >
          *.docker.com:443
          *.docker.io:443
          api.github.com:443
          cdn.datatables.net:443
          cdn.jsdelivr.net:443
          code.jquery.com:443
          github.com:443
          objects.githubusercontent.com:443

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"

    - name: Fetch external JS deps
      run: go run bin/fetchclientdeps/fetchclientdeps.go

    # TODO: maybe install sqlc, templ, and tsc code generation
    #  here as well. They would add some additional build time
    #  (mostly due to fetching their deps and building them),
    #  which is less than ideal. For now, it should be fine to
    #  do these on the developer's computer, and this can be
    #  enforced by pre-commit.

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
